### PR TITLE
Add css definition to be read off of data, so it can handle abstract …

### PR DESCRIPTION
**Pull request by hyunlim**
…and child states
## Summary
Made the change to read css off of `data` property so it can be inherited off of parent states.

### CODE REVIEW

**Comment by kaiku** [comment]
Instead of merging to `master` I'd recommend creating a new Lyft-specific branch into which you merge this code. Keeping our fork's `master` in sync with the upstream `master` means we can more easily open upstream PRs that don't include any Lyft-specific, non-upstream-merged changes we've added for our use.

I believe this is the preferred way to do this, cc @zimathias and @ryan-lane.

:+1: for the code

**Comment by ryan-lane** [comment]
Yes. Please don't merge to master of public forks.

**Comment by hyunlim** [comment]
@ryan-lane @kaiku any naming conventions for lyft's master?  Otherwise, I'll merge it to `lyft-master`, and use that as the main fork for now.

**Comment by kaiku** [comment]
@hyunlim `lyft-master` sounds good to me

**Comment by hyunlim** [comment]
going to create another PR

**Pull request closed without merging**
